config(tests): require pundit only on policy specs
This avoids having a NoMethodError: undefined method `deprecator' for
module ActiveSupport.
This errors popped when upgrading from Rails 7.0 to Rails 7.1